### ISSUE TITLE
gulp serve (copy part) is slow

### ISSUE THREAD

**Issue by romain10009** [ndelvalle/generator-api#10]
Hi! When I run gulp serve, I see the following on my project : 

![image](https://cloud.githubusercontent.com/assets/7512202/18013899/a444daa0-6bc0-11e6-9cac-188808d5ed2e.png)

It doesn't have lots of files to move (only two models / routes etc... ) It is slow since the verry first use.

**Comment by ndelvalle** [comment]
Hey @romain10009 why are running `gulp serve`. I don't make use of gulp in this project just npm scripts. Assuming you already run the generator, run `npm run dev` to start the project in dev mode.
