### ISSUE TITLE
module structure option?

### ISSUE THREAD

**Issue by djchrispurple** [ndelvalle/generator-api#12]
great job !
what about the option of getting the files structured by modules (users, customers, etc )
and not by type of file ( models, controllers, etc)
thanks
Chris

**Comment by ndelvalle** [comment]
Yes I would definitely like to implement this, I'm not sure if use this approach as default or make it configurable.

**Comment by ndelvalle** [comment]
@djchrispurple I have implemented this in the last release #13. Feel free to test it out and let me know what you think 🙂

**Comment by djchrispurple** [comment]
great job !!
