### ISSUE TITLE
How to deploy the API with nginx on Ubuntu?

### ISSUE THREAD

**Issue by eBaeza** [ndelvalle/generator-api#14]

**Comment by ndelvalle** [comment]
Hi @eBaeza I actually haven't done that yet. Are you having problems with something in particular? Or you don't know how to start? Here I found an [interesting article ](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04). Let me know if it helps you.

**Comment by eBaeza** [comment]
Thank you @ndelvalle I just do not know where to start but the article helped me.

**Comment by ndelvalle** [comment]
@eBaeza Do you have to deploy it that way for a particular reason? You can use Heroku and have the app working in 1 minute. I can help you with that 👍

**Comment by eBaeza** [comment]
yes, I develop a mini-API for a hackathon where I participated, so we used an image with ubuntu in a virtual machine.
