### ISSUE TITLE
Models file naming

### ISSUE THREAD

**Issue by gillchristian** [ndelvalle/generator-api#32]
This is how model files are named now:
```
└───model/
    ├───user/
        └───user-controller.js
        └───user-facade.js
        └───user-router.js
        └───user-schema.js
```

I was just wondering since the directory already is named after the model, I think it would make sense to remove the model name from the files:

```
└───model/
    ├───user/
        └───controller.js
        └───facade.js
        └───router.js
        └───schema.js
```

What do you think @ndelvalle ?

**Comment by martincarrera** [comment]
#33

**Comment by martincarrera** [comment]
Hey @ndelvalle, I'm not sure if you want to go with this, I created the PR #33 in order to fix this.

**Comment by gillchristian** [comment]
Close in favor of #33
