### ISSUE TITLE
/resource/:id wrong behaviour

### ISSUE THREAD

**Issue by fyyyyy** [ndelvalle/generator-api#4]
The search results wont be correct as current route defaults for /resource/:id use findOne (with the req.query which is blank for this route)

Instead routes should use findById with the req.params.id to deliver the correct response

```
// routes.js
router.route('/events/:id')
    .get((...args) => controllers.event.findById(...args));
```

**Comment by ndelvalle** [comment]
Thanks @fyyyyy for reporting the error. You can get the last version from npmjs.
