### ISSUE TITLE
Idea for security (Help / Suggestion needed)

### ISSUE THREAD

**Issue by aceymer** [ndelvalle/generator-api#8]
This is an awesome project.
How would you handle security and could you make a version where there could be a choice to scaffold security?

Thanks

**Comment by ndelvalle** [comment]
Hy @aceymer, I think I should add this functionality to the generator. I would use a token based authentication, with something like JSON Web Tokens. 
Here there are some resources to get you started with it, if you want to implement it right away.
* [Scotch Tutorial](https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens)
* [jwt Webpage](https://jwt.io/introduction/)

Don't doubt to contact me if you need help with that 👍
